### PR TITLE
Support for 480p devices (Especially Android One)

### PR DESCRIPTION
**Pull request by ShankarWarang**

### CODE REVIEW

**Comment by ShankarWarang** [comment]
Bro, how to upload vendor/nitrogen/prebuilt/common/480.zip? I made it by resizing and its working

**Comment by xyyx** [comment]
send to xyyx@mail.ru. I will update commit

**Comment by ShankarWarang** [comment]
I want to upload 480.zip in vendor/nitrogen/prebuilt/bootanimation. How to
do it? 480p bootanimation is working on Android One

**Comment by ShankarWarang** [comment]
Sent bro

**Pull request merged**
